# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Win

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x' # Usa la versión apropiada
          
      - name: Build .NET 6.x
        run: |
          dotnet restore
          dotnet build SharkGo/SharkGo.csproj --configuration Release --framework net6.0 
          dotnet publish SharkGo/SharkGo.csproj --configuration Release --framework net6.0 --output ./Sharkgo/publish/net6.0

      - name: List files before unzip
        run: ls -R /Users/runner/work/SharkGo/
      - name: Unzip SharkGo.app.zip
        run: unzip /Users/runner/work/SharkGo/SharkGo/SharkGo.app.zip -d /Users/runner/work/SharkGo/SharkGo
        
      - name: Copy files to SharkGo.app
        run: |
          mkdir -p /Users/runner/work/SharkGo/SharkGo/SharkGo.app/Contents/MacOS/bin         
          cp -r /Users/runner/work/SharkGo/SharkGo/SharkGo/bin/Release/net6.0/* /Users/runner/work/SharkGo/SharkGo/SharkGo.app/Contents/MacOS/bin/
          cp /Users/runner/work/SharkGo/SharkGo/SharkGo/bin/Release/net6.0/runtimes/osx-x64/native/* /Users/runner/work/SharkGo/SharkGo/SharkGo.app/Contents/MacOS/bin/
          rm -r /Users/runner/work/SharkGo/SharkGo/SharkGo.app/Contents/MacOS/bin/runtimes
      - name: List files after copying
        run: ls -R /Users/runner/work/SharkGo/SharkGo/SharkGo.app/
        
      - name: Create DMG
        run: |
          hdiutil create -srcfolder /Users/runner/work/SharkGo/SharkGo/SharkGo.app -volname SharkGo -format UDZO ./SharkGo.dmg
          
      - name: List files in publish directory
        run: ls -R /Users/runner/work/SharkGo/

      - name: Upload Release Artifact .NET 6.0 and Compressed Files
        uses: actions/upload-artifact@v2
        with:
          name: release-artifact-net6.0
          path: |
            ./SharkGo/publish
            
      - name: Create Or Update Release
        id: create_release
        uses: joutvhu/create-release@v1.0.0
        with:
          tag_name: Beta
          name: Beta Release
          draft: false
          on_release_exists: update
          remove_assets: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./SharkGo/SharkGo.dmg
          asset_name: SharkGo_Beta-macOS-x64.dmg
          tag: ${{ steps.create_release.outputs.tag_name }}  # Obtén el nombre de la etiqueta del paso anterior
          overwrite: true  # Sobrescribe el archivo si ya existe en el lanzamiento
