# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Win

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x' # Usa la versión apropiada
          
      - name: Build and Publish .NET 6.0
        run: |
          cd SharkGo
          dotnet restore
          dotnet build --configuration Release --framework net6.0
          dotnet publish --configuration Release --framework net6.0 --output ./publish/net6.0

      - name: Compress Files
        run: |
          #ls -R 
          cd ./SharkGo/publish/net6.0
          Compress-Archive -Path gpx, runtimes, Aspose.GIS.dll, Fleck.dll, ICSharpCode.SharpZipLib.dll, iMobileDevice-net.dll, Newtonsoft.Json.dll, plist-cil.dll, SharkGo.deps.json, SharkGo.dll, SharkGo.exe, SharkGo.pdb, SharkGo.runtimeconfig.json -DestinationPath ../../SharkGoFiles.zip
          cd ../..

      - name: List files in publish directory
        run: ls -R ./SharkGo

      - name: Upload Release Artifact .NET 6.0 and Compressed Files
        uses: actions/upload-artifact@v2
        with:
          name: release-artifact-net6.0
          path: |
            ./SharkGo/publish

      - name: Get Last Commit
        id: last_commit
        run: echo "commit=$(git log -1 --pretty=format:'%h - %s')" >> $GITHUB_OUTPUT

      - name: Get Last Push Date
        id: last_push
        run: echo "push_date=$(git log -1 --pretty=format:'%cd' --date=short)'" >> $GITHUB_OUTPUT

      - name: Update Release
        id: create_release
        uses: joutvhu/create-release@v1.0.0
        with:
          tag_name: Auto
          name: "Beta Release - ${{ steps.last_push.outputs.push_date }} -"
          draft: false
          on_release_exists: update
          remove_assets: false
          prerelease: true
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     - name: Upload Files
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./SharkGo/SharkGoFiles.zip
          asset_name: SharkGo_Beta-Windows-x86-x64.zip
          tag: ${{ steps.create_release.outputs.tag_name }}  # Obtén el nombre de la etiqueta del paso anterior
          overwrite: true  # Sobrescribe el archivo si ya existe en el lanzamiento
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

